### ISSUE TITLE
Mismatched SHA

### ISSUE THREAD

**Issue by helenvholmes** [jingweno/ccat#14]
I was going through the installation instructions with brew but get a mismatch SHA error on install:

![screen shot 2015-05-08 at 9 33 56 am](https://cloud.githubusercontent.com/assets/1720093/7537249/5bb4b986-f565-11e4-82a9-0a48622388de.png)

I removed the tar file as it suggests but no dice. Any ideas on what might be happening?

Thanks!

**Comment by jingweno** [comment]
Could you do a `brew update`? The latest version is v0.0.3. I might skewed the formula at some point.

**Comment by helenvholmes** [comment]
That worked like a charm! Thank you very much!

**Comment by jingweno** [comment]
:metal:
