### ISSUE TITLE
Fail to install on OSX (homebrew)

### ISSUE THREAD

**Issue by martinlindhe** [jingweno/ccat#2]
```
> brew tap jingweno/ccat
==> Tapping jingweno/ccat
Cloning into '/usr/local/Library/Taps/jingweno/homebrew-ccat'...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
Checking connectivity... done.
Tapped 1 formula (26 files, 108K)

> brew install ccat
==> Installing ccat from jingweno/homebrew-ccat
==> Downloading https://github.com/jingweno/ccat/archive/v0.0.1.tar.gz
######################################################################## 100.0%
==> go build -o ccat
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/codegangsta/cli (from $GOROOT)
	/Users/m/dev/goPlay/src/github.com/codegangsta/cli (from $GOPATH)
printer.go:7:2: cannot find package "github.com/sourcegraph/syntaxhighlight" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/sourcegraph/syntaxhighlight (from $GOROOT)
	/Users/m/dev/goPlay/src/github.com/sourcegraph/syntaxhighlight (from $GOPATH)

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/jingweno/homebrew-ccat/issues
```

**Comment by benjy** [comment]
Same error here.

**Comment by martinlindhe** [comment]
resolved by manually doing:

   go get github.com/sourcegraph/syntaxhighlight

then "brew instal ccat" continues;

```
> brew install ccat
==> Installing ccat from jingweno/homebrew-ccat
==> Downloading https://github.com/jingweno/ccat/archive/v0.0.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/ccat-0.0.1.tar.gz
==> go build -o ccat
go build -o ccat

main.go:11:2: cannot find package "github.com/codegangsta/cli" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/codegangsta/cli (from $GOROOT)
	/Users/m/dev/goPlay/src/github.com/codegangsta/cli (from $GOPATH)

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/jingweno/homebrew-ccat/issues
```

**Comment by martinlindhe** [comment]
resolved by manually:

    go get github.com/codegangsta/cli

now "brew install ccat" succeeds

**Comment by benjy** [comment]
That still gives me a similar issue about GOPATH, what's the default location for that?

╰─➤  go get github.com/codegangsta/cli                                                                        1 ↵
package github.com/codegangsta/cli: cannot download, $GOPATH not set. For more details see: go help gopath

**Comment by martinlindhe** [comment]
@benjy ah, that means you need to a initial setup for golang,
see "brew show go", specially the last part:

```
==> Caveats
As of go 1.2, a valid GOPATH is required to use the `go get` command:
  https://golang.org/doc/code.html#GOPATH

You may wish to add the GOROOT-based install location to your PATH:
  export PATH=$PATH:/usr/local/opt/go/libexec/bin
```

**Comment by benjy** [comment]
Thanks, that fixed a few issues, I did a couple more go get's to get the syntax highlighting dependency and no I have a new error:

─➤  brew install ccat
==> Installing ccat from jingweno/homebrew-ccat
==> Downloading https://github.com/jingweno/ccat/archive/v0.0.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/ccat-0.0.1.tar.gz
==> go build -o ccat

go build -o ccat

# _/private/tmp/ccat20150506-71841-7xo3gg/ccat-0.0.1
./main.go:11: import /Users/benjy/go/pkg/darwin_amd64/github.com/codegangsta/cli.a: object is [darwin amd64 go1.4 X:precisestack] expected [darwin amd64 go1.4.2 X:precisestack]

**Comment by remmelt** [comment]
I think it's complaining about your version of go. 

Try: `brew update && brew upgrade go`
or indeed `brew upgrade --all`

**Comment by benjy** [comment]
I tried that before I posted but no luck.

    ╰─➤  brew update                                                                                                                                                   
    Updated Homebrew from 8d1385b1 to e56ff908.
    ==> Updated Formulae
    ╰─➤  brew upgrade go
    Error: go 1.4.2 already installed

**Comment by minbyulcat** [comment]
resolved above by manually

```
export GOPATH=$HOME

go get github.com/codegangsta/cli

brew install mercurial # hg for syntaxhighlight
go get github.com/sourcegraph/syntaxhighlight

brew install ccat
```

**Comment by benjy** [comment]
Yeah, they were the exact commands I ran, apart from I had GOPATH=$HOME/go, unfortunately no better off though.

**Comment by AntouanK** [comment]
I also got the `GOPATH` error.
[Solution](https://github.com/jingweno/ccat/issues/2#issuecomment-99391665) from @minbyulcat solved it

From what I understand we must have `go` installed in our machine, right?
Why do you assume that we already have it?
Shouldn't the `go` installation step be included in the instructions?
Or should it be installed by brew as a dependancy?

**Comment by poliveira89** [comment]
For me, even with `GOPATH` and `GOROOT` defined as environment variables, the install as mention on README.md does network without manual intervention.

So I did what @minbyulcat shared. And after that the `brew install cat` worked.

**Comment by jingweno** [comment]
The formula is fixed in https://github.com/jingweno/homebrew-ccat/issues/1#issuecomment-99489949. Please run a `brew update` and reinstall again.

Let me know if you still run into issue :beer:
