### ISSUE TITLE
ccat pipe into less not coloring syntax

### ISSUE THREAD

**Issue by cdipaolo** [jingweno/ccat#22]
Title is pretty self explanatory but if you ```ccat file.go | less``` the scrollable text is not colored. Not entirely sure if you can color something and then pipe it but if you can it would be a nice feature to run through long files using less to scroll

**Comment by jingweno** [comment]
Ah, this is because we disable syntax highlighting when `ccat` is [not running in a terminal](https://github.com/jingweno/ccat/blob/master/ccat.go#L36), e.g., `ccat file.go > foo`. I think we might have to provide a flag instead of making this decision for the user.

/cc @mattn @gilliek

**Comment by mattn** [comment]
if stdout is not a terminal, go-colorable on window output ansi color codes as given. So if you add new flag to output ansi escape sequence forcely, it should work correctly. :)

**Comment by jingweno** [comment]
Just have another thought, how about making it something like `ccat FILE -exec less` while things like `ccat FILE | less` or `ccat FILE | less` still disable syntax highlighting?

**Comment by Rolinh** [comment]
@jingweno Why reinvent the wheel? This is a well know and already solved problem. Why not do like most other toolsdo? =>  `--color=always` if you want to always have colors, `--color=never` if you don't want colors with `--color=auto` by default. And you could use `-c always` for short for instance.

**Comment by jingweno** [comment]
@Rolinh Yes, this is what I suggested [here](https://github.com/jingweno/ccat/pull/9#issuecomment-99633176). I'm laying out all the options here for evaluation.

**Comment by Rolinh** [comment]
@jingweno It's similar except that your solution is boolean so there is no way to say "always", "never" or "auto". I think your proposition [here](https://github.com/jingweno/ccat/issues/22#issuecomment-102847805) does not make any sense :) .

**Comment by jingweno** [comment]
> It's similar except that your solution is boolean so there is no way to say "always", "never" or "auto"

I'm actually not following the "never" and "auto" flag. If it's "never", you wouldn't need to use `ccat` (just fallback to `cat`).

**Comment by jingweno** [comment]
I provided a solution [here](https://github.com/jingweno/ccat/pull/24).
