### ISSUE TITLE
conflicting formulas

### ISSUE THREAD

**Issue by martinlindhe** [jingweno/ccat#23]
seems formula have been added upstream: https://github.com/Homebrew/homebrew/commit/f8e10bbd42a9eeae801499fbfdb27e49b9b88c5e

```
> brew update; brew upgrade
Warning: Could not create link for jingweno/ccat/ccat, as it
conflicts with Homebrew/homebrew/ccat. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install jingweno/ccat/ccat
Updated Homebrew from 84dd2e2f to d956958c.
==> New Formulae
ccat
...
```

one solution is to remove this tap:

  brew untap jingweno/ccat

**Comment by jingweno** [comment]
That's right. It was accepted to upstream. I have [updated the README](https://github.com/jingweno/ccat/commit/67b77c43cb750de66bf20c5712994971978894b6).
