### ISSUE TITLE
Disable colouring while piping

### ISSUE THREAD

**Issue by JikkuJose** [jingweno/ccat#25]
I think its sort of standard to avoid colour while the output is passed to a pipe. It helps in further processing of the data. I understand it may be handy while piping to `less` or so. But most of the time, its better to be avoided.

Perhaps provide a flag and disable in by default.

**Comment by jingweno** [comment]
@JikkuJose This is implemented in the latest master: https://github.com/jingweno/ccat/pull/24 where by default it doesn't output color when the output is not a terminal. There're also options to always enable or disable coloring. Is this what you're looking for?

**Comment by JikkuJose** [comment]
Yes! Thanks!
