### ISSUE TITLE
What would happen if I aliased cat to ccat?

### ISSUE THREAD

**Issue by aroman** [jingweno/ccat#30]
I love ccat, and I'm wondering what the consequences of setting an alias in my shell for `cat` -> `ccat` would be? Would the performance hit be significant? Might I run into encoding issues? Is this just a terrible idea?

**Comment by jingweno** [comment]
It's a great idea and I'm aliasing `ccat` to `cat` on my box:

```
alias cat=ccat
```

The overhead is minimum:

```
$ wc -l main.go
123 main.go
$ time cat main.go > /dev/null
cat main.go > /dev/null  0.00s user 0.00s system 61% cpu 0.005 total
$ time ccat main.go > /dev/null
ccat main.go > /dev/null  0.00s user 0.00s system 78% cpu 0.007 total
```

You can always fall back to `cat` after aliasing it by typing `\cat`. I'm not sure what you meant by encoding issues.

**Comment by aroman** [comment]
everything I wanted to know and more. thanks again!

**Comment by jingweno** [comment]
I added more description in this topic in the readme: https://github.com/jingweno/ccat/commit/bf0f28e7d7496ff2dd36f5e9e96bf8791d9f3987

**Comment by aroman** [comment]
great :+1:
