### ISSUE TITLE
Pager

### ISSUE THREAD

**Issue by srid** [jingweno/ccat#38]
What is the recommended way to page through the output of ccat? `ccat README.md | less -R` for example does not work (no colors) even though it works for `cat my.patch | colordiff | less -R`. 

Or would it make more sense to integrate pager into ccat (`ccat -p README.md`)?

**Comment by jingweno** [comment]
[This](https://github.com/jingweno/dotfiles/blob/master/.zshrc#L78) is what I do.

> Or would it make more sense to integrate pager into ccat (ccat -p README.md)?

`less` has done a great job of paging so a combination of `ccat` and `less` like above should do the trick.

**Comment by srid** [comment]
Oh, so it was disabling colors automatically if stdout is not a term. I did not know about `--color=always`.
