### ISSUE TITLE
ccat /directory/name doesn't warn that target is a directory

### ISSUE THREAD

**Issue by yyaabboopp** [jingweno/ccat#39]
`ccat /directory/name` does not warn that the target is a directory – it simply returns with exit code 0 and nothing printed to screen. While not a serious issue, considering the user will likely discover their error, it does have potential to cause unnecessary confusion.

`cat` returns the following: `cat: /directory/name: Is a directory` with exit code 1

OS X 10.11.5 / ccat v1.1.0

**Comment by jingweno** [comment]
Fixed in https://github.com/jingweno/ccat/pull/40.
