### ISSUE TITLE
Error: Calling Formula.sha1 is disabled!

### ISSUE THREAD

**Issue by volkanunsal** [jingweno/ccat#47]
I started getting this error today. I think you need to release a new version.

```text
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/jingweno/homebrew-ccat/ccat.rb:6:in `<class:Ccat>'
Please report this to the jingweno/ccat tap!
```

**Comment by jingweno** [comment]
Please remove the `brew untap jingweno/ccat` to remove the old formula and use the official one with `brew install ccat`.
