### ISSUE TITLE
Check this

### ISSUE THREAD

**Issue by nvartolomei** [jingweno/ccat#5]
alias ccat="pygmentize -O style=monokai -f console256 -g"

**Comment by jingweno** [comment]
Hey, I know about `pygmentize`. I added [a FAQ section](https://github.com/jingweno/ccat#why-not-pygments) to clarify a bit. Basically `ccat` is an *nix alternative to `pygmentize`. Of course this is more of a philosophy preference  :beer:

**Comment by nvartolomei** [comment]
No problem, just wanted to remind you about this awesome alias 😇
