### ISSUE TITLE
ccat command is already taken by ccrypt package on Ubuntu/Debian

### ISSUE THREAD

**Issue by beberlei** [jingweno/ccat#7]

**Comment by jingweno** [comment]
Hmm....bumper, `scat` (Syntax highlighting cat) is also taken...I need to think of a cooler and unique name...

**Comment by pixelr0** [comment]
cats? cats>cat

**Comment by AustinDizzy** [comment]
@jingweno Regardless of its availability, I would advise against using `scat`. A quick Google search will tell you why... Maybe `syntac` or `syncat` for a play on cat and syntax?

Or you could go a different route and just call it `cat` and aim for making this essentially just an enhanced cat in Go. Then, as long as your $GOPATH is before `/bin` in your $PATH, your version of cat will override the system default.
If you choose to go that route, then it'd also be in your best interest to support all the flags and options [cat(1)](http://linux.die.net/man/1/cat) does to make it more of a replacement for cat.

**Comment by phaikawl** [comment]
*catsy*?

**Comment by wdawson4** [comment]
@AustinDizzy i would recommend against naming this cat replacing cat with this package.
To make the syntax highlighting work, it injects ANSI escape sequences into the text. 
The ANSI escape sequences will cause you all kinds of issues piping from cat
For example:
```bash
local:~ wdawson$ echo "hello world" | base64 > hello_world64
local:~ wdawson$ cat hello_world64 | base64 --decode
hello world
local:~ wdawson$ ccat hello_world64 | base64 --decode
Invalid character in input stream.
local:~ wdawson$ ccat hello_world64
aGVsbG8gd29ybGQK
```

**Comment by wdawson4** [comment]
what about prettycat?

**Comment by KeizerDev** [comment]
How about `catlight`?

**Comment by AustinDizzy** [comment]
@wdawson4 Using IsTerminal from golang.org/x/crypto/ssh/terminal ([docs here](https://godoc.org/golang.org/x/crypto/ssh/terminal#IsTerminal)), you can tell if the program's output is being piped. Using that, we can set a check in main.go#ccat to return only the file's contents without syntax highlighting if the output is being piped. Then possibly a flag to output using the ANSI sequences regardless of whether the output is being piped or not.



-----Original Message-----

**Comment by mattn** [comment]
This will be fixed by https://github.com/jingweno/ccat/pull/12

**Comment by hut8** [comment]
:+1: for `scat` :hankey:

**Comment by jingweno** [comment]
Haha, :+1: to scat, but unfortunately ccat has already been released to the public, need a plan to safely migrate if we decide to do this

**Comment by mattn** [comment]
This is closable.

**Comment by jingweno** [comment]
Closing.

**Comment by astubbs** [comment]
So sorry, what was the solution for ubuntu package management?

**Comment by astubbs** [comment]
A I see, welcome to the world of AUR and PPA's.. I saw the PPA comment in another issue here.
